name: Release

on:
  # Support manually pushing a new release
  workflow_dispatch: {}
  # Trigger when a release is published
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest

    name: Publish to NPM

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Clean install dependencies
        run: |
          npm ci

      - name: Run tests
        run: |
          npm run test

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
