name: Release

on:
  # Support manually pushing a new release
  workflow_dispatch: {}
  # Trigger when a release is published
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest

    name: Publish to NPM

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update blutui.ts version
        run: sed -i "s/const VERSION = '.*';/const VERSION = '${{ github.ref_name }}';/g" src/blutui.ts

      - name: Commit version change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update version to v${{ github.ref_name }}"

      - name: Push changes
        run: git push
